export const countries = [
    { code: 'US', name: 'United States', flag: '🇺🇸' },
    { code: 'GB', name: 'United Kingdom', flag: '🇬🇧' },
    { code: 'CA', name: 'Canada', flag: '🇨🇦' },
    { code: 'CH', name: 'Switzerland', flag: '🇨🇭' },
    { code: 'DE', name: 'Germany', flag: '🇩🇪' },
    { code: 'SE', name: 'Sweden', flag: '🇸🇪' },
    { code: 'DK', name: 'Denmark', flag: '🇩🇰' },
    { code: 'AU', name: 'Australia', flag: '🇦🇺' },
    { code: 'NO', name: 'Norway', flag: '🇳🇴' },
    { code: 'SG', name: 'Singapore', flag: '🇸🇬' },
    { code: 'NL', name: 'Netherlands', flag: '🇳🇱' },
    { code: 'FI', name: 'Finland', flag: '🇫🇮' },
    { code: 'IE', name: 'Ireland', flag: '🇮🇪' },
    { code: 'AT', name: 'Austria', flag: '🇦🇹' },
    { code: 'BE', name: 'Belgium', flag: '🇧🇪' },
    { code: 'NZ', name: 'New Zealand', flag: '🇳🇿' },
    { code: 'JP', name: 'Japan', flag: '🇯🇵' },
    { code: 'KR', name: 'South Korea', flag: '🇰🇷' },
    { code: 'FR', name: 'France', flag: '🇫🇷' },
    { code: 'IT', name: 'Italy', flag: '🇮🇹' },
    // High-population countries with growing luxury markets
    { code: 'CN', name: 'China', flag: '🇨🇳' },
    { code: 'IN', name: 'India', flag: '🇮🇳' },
    { code: 'BR', name: 'Brazil', flag: '🇧🇷' },
    { code: 'AE', name: 'United Arab Emirates', flag: '🇦🇪' },
    { code: 'SA', name: 'Saudi Arabia', flag: '🇸🇦' },
];  